on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - run: |
        mvn clean verify --no-transfer-progress
    - uses: actions/upload-artifact@v4
      with:
        name: jar
        path: target/aws-cloudformation-template-schema-1.0-SNAPSHOT-jar-with-dependencies.jar
